Addition of License File
NOAA-GFDL/PySHiELD pull request #23
Opened 2024-11-22 16:22 UTC by fmalatino

**Description**
Added Apache 2.0 license text 

Fixes # 22
This PR addresses 22

**How Has This Been Tested?**
No changes to functionality of code

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] Targeted model, if this change was triggered by a model need/shortcoming

2024-11-25 13:51 UTC, FlorianDeconinck commented on LICENSE.md
> +   Copyright 2022 Allen Institute for Artificial Intelligence (AI2)
This needs to go

2024-11-25 16:41 UTC, fmalatino commented on LICENSE.md
> +   Copyright 2022 Allen Institute for Artificial Intelligence (AI2)
Just the copyright and reference to AI2? Or more?

2024-11-27 20:49 UTC, FlorianDeconinck commented on LICENSE.md
> +   Copyright 2022 Allen Institute for Artificial Intelligence (AI2)
The copyright yeah

2024-11-29 16:47 UTC, FlorianDeconinck submitted a review, later dismissed
LGTM

2024-12-02 12:34 UTC, bensonr submitted a review, later dismissed

2024-12-02 14:42 UTC, oelbert requested changes
I think we should update the author list and contact info as well if we're updating the licensing

2024-12-02 14:42 UTC, oelbert commented on setup.py
>      classifiers=[
We should change this

2024-12-02 14:46 UTC, fmalatino commented on setup.py
>      classifiers=[
Is there something it should be?

2024-12-02 18:00 UTC, oelbert commented on setup.py
>      classifiers=[
Ugh it didn't highlight the whole portion I wanted. Basically replace 
```
setup(
     author="Vulcan Technologies LLC",
    author_email="elynnw@vulcan.com",
    python_requires=">=3.11.7",
    classifiers=[
```
with 
```
setup(
    author="NOAA - Geophysical Fluid Dynamics Laboratory",
    author_email="oliver.elbert@noaa.gov",
    python_requires=">=3.11.7",
    classifiers=[
```

2024-12-02 18:00 UTC, oelbert commented on setup.py
>      classifiers=[
Or anyone else who wants to be Point of Contact ;-)

2024-12-06 15:02 UTC, oelbert approved these changes
👍

2024-12-06 15:16 UTC, merged